eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental
    username: prem
    password: 123789ad
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    .
    hibernate:
      ddl-auto: create
